name: quantum-computing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - matplotlib
  - scikit-learn
  - sympy
  - pytorch
  - pip:
      - mlflow
      - psycopg[binary]
      - pennylane==0.44.1
      - qiskit==2.3.0
      - pylatexenc
      - tqdm
